### ISSUE TITLE
deport api client config from hero service

### ISSUE THREAD

**Issue by raphaeldenis** [Olivier-Nouvel-GitHub/project-marvel#1]
also the service maybe could be named hero.service.ts?

https://github.com/Olivier-Nouvel-GitHub/project-marvel/blob/f3ecbf69170c18b70ea834fbaab42fb2af6dbc7e/src/services/Api.tsx#L12

**Comment by Olivier-Nouvel-GitHub** [comment]
Indeed, the changes have been done.
